name: build and test
on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Setup
        run: |
          npm run setup:mongo
          docker ps

      - name: Test:main
        run: |
          npm run test:main;

      - name: Test:e2e
        run: |
          npm run test:e2e
