name: build and test
on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      CALIBRATION_LOTUS_API_ENDPOINT: ${{ vars.CALIBRATION_LOTUS_API_ENDPOINT }}
      CALIBRATION_LOTUS_PROVIDER_URL: ${{ vars.CALIBRATION_LOTUS_PROVIDER_URL }}
      CALIBRATION_MONGO_URL: ${{ vars.CALIBRATION_MONGO_URL }}
      CALIBRATION_PROD_MONGO_URL: ${{ vars.CALIBRATION_PROD_MONGO_URL }}
      CALIBRATION_START_HEIGHT: ${{ vars.CALIBRATION_START_HEIGHT }}
      MAIN_LOTUS_API_ENDPOINT: ${{ vars.MAIN_LOTUS_API_ENDPOINT }}
      MAIN_LOTUS_PROVIDER_URL: ${{ vars.MAIN_LOTUS_PROVIDER_URL }}
      MAIN_MONGO_URL: ${{ vars.MAIN_MONGO_URL }}
      MAIN_PROD_MONGO_URL: ${{ vars.MAIN_PROD_MONGO_URL }}
      MAIN_START_HEIGHT: ${{ vars.MAIN_START_HEIGHT }}
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Setup
        run: |
          npm run setup:mongo
          docker ps

      - name: Test:main
        run: |
          npm run test:main;

      - name: Test:e2e
        run: |
          npm run test:e2e
